dropdrive.version=${project.version}
dropdrive.file.upload.retries=3
dropdrive.core.drive.redirectUri.port=8783
dropdrive.core.drive.redirectUri.context=/dropdrive
dropdrive.core.drive.redirectUri=http://127.0.0.1:${dropdrive.core.drive.redirectUri.port}${dropdrive.core.drive.redirectUri.context}