dropdrive.core.drive.clientKey=x5tsbub2tui7zmz
dropdrive.core.drive.clientSecret=fhluvhpn5abmy74
dropdrive.core.drive.redirectUri.port=8783
dropdrive.core.drive.redirectUri.context=/dropdrive
dropdrive.core.drive.redirectUri=http://127.0.0.1:${dropdrive.core.drive.redirectUri.port}${dropdrive.core.drive.redirectUri.context}